### ISSUE TITLE
No appropriate error for install fail

### ISSUE THREAD

**Issue by clample** [appium/appium-selendroid-driver#15]
Installing appium-selendroid-driver 1.2.2 fails without java developer kit installed. There is no clear error output saying that this is why the install failed.

os: ubuntu 
Node version: 4.1.2
npm version: 2.14.4

[appium-selendroid-driver-install-error.txt](https://github.com/appium/appium-selendroid-driver/files/156468/appium-selendroid-driver-install-error.txt)

**Comment by imurchie** [comment]
Good point. Thanks!

**Comment by rkavalap** [comment]
![appiuminstallerror](https://cloud.githubusercontent.com/assets/80310/13767188/5387112c-ea25-11e5-820f-973b4041ab15.JPG)

**Comment by rkavalap** [comment]
I have open jdk 8 installed on debian, yet received the above error on trying to install appium.

**Comment by imurchie** [comment]
Is `jar` in your path?

**Comment by rkavalap** [comment]
@imurchie

I believed I installed the jdk. But apparently i did not. So I took a closer look at my packages.
it was "openjdk-8-jre". grrr. 

That answers the question of jar file not available in my path. Installed the actual jdk, and appium installed fine.

**Comment by jtappi** [comment]
Hi all,

I am running into the same issue on my Windows System.  The error message is the same as the one above.  I have verified that I have the Java SDK installed and that the Environment Variable do point to C:\Program Files\Java\jdk1.8.0_74.  Are there any other items I can try to get appium to install on my system?  I have attached my log file with the error message that is returned when installing appium.  thanks

**Comment by imurchie** [comment]
I don't see any error logs, @jtappi

**Comment by jtappi** [comment]
Thanks for the quick reply @imurchie .  For some reason my attachments will not show up.  Fortunately, I found that adding the \bin after the JDK in my path variable helped resolve the issue.

So...

My PATH value included (%JAVA_HOME%\bin)
and my JAVA_HOME value contains the JDK location (C:\Program Files\Java\jdk1.8.0.74)

**Comment by imurchie** [comment]
Excellent. Thanks for letting us know.
