### ISSUE TITLE
Error at "node ./bin/install.js"

### ISSUE THREAD

**Issue by Domuska** [appium/appium-selendroid-driver#31]
I was attempting to install appium with npm with command 
`npm install -g appium`

All went well, but after "determining AndroidManifest location"  npm spat out an error as such:

`Error: Command 'jar tf C:\\Users\\username\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\appium-selendroid-driver\\node_modules\\appium-selendroid-installer\\selendroid\\download\\selendroid-server.jar' errored out: Error: spawn jar ENOENT`
`    at exports._errnoException (util.js:870:11)`
`    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)`
`    at onErrorNT (internal/child_process.js:344:16)`
`    at nextTickCallbackWith2Args (node.js:442:9)`
`    at process._tickCallback (node.js:356:17)`
`    at ChildProcess.<anonymous> (lib/teen_process.js:31:14)`
`    at emitOne (events.js:77:13)`
`    at ChildProcess.emit (events.js:169:7)`
`    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)`
`    at onErrorNT (internal/child_process.js:344:16)`
`    at nextTickCallbackWith2Args (node.js:442:9)`
`    at process._tickCallback (node.js:356:17)`
`npm ERR! Windows_NT 10.0.10240`
`npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "appium"`
`npm ERR! node v4.4.5`
`npm ERR! npm  v2.15.5`
`npm ERR! code ELIFECYCLE`

`npm ERR! appium-selendroid-driver@1.3.4 install: node ./bin/install.js`
`npm ERR! Exit status 1`
`npm ERR!`
`npm ERR! Failed at the appium-selendroid-driver@1.3.4 install script 'node ./bin/install.js'.`
`npm ERR! This is most likely a problem with the appium-selendroid-driver package,`
`npm ERR! not with npm itself.`
`npm ERR! Tell the author that this fails on your system:`
`npm ERR!     node ./bin/install.js`

Any advice on this?

**Comment by imurchie** [comment]
Do you have the bin directory of your JAVA_HOME on your PATH? Can you run `jar` from the command line?

**Comment by Domuska** [comment]
Hi, thanks for the quick answer, I did seem to completely neglect setting the bin folder to my path, the installation worked well after adding that. Thanks!
